---
name: TeamCity Config Test

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/teamcity-test.yaml'
      - '!.teamcity/components/generated/**'
      - '!.teamcity/target/**'
      - '.teamcity/**'

concurrency:
  group: 'tctest-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  teamcity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: make teamcity-test
